server:
  port: 8081
spring:
  application:
    name: ms-email
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/email
    username: postgres
    password: root
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: netero.elder@gmail.com
    password: Netero@Elderly1920
    protocol: smtp
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
