server:
  port: 8081
spring:
  application:
    name: ms-email
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/email
    username: root
    password: mysql
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: netero.elder@gmail.com
    password: Netero@Elderly1920
    protocol: smtp
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
